### ISSUE TITLE
Your assignment three does not guarantee that the list is not empty

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/elm-assignment-luukverberkt#1]
You chose to wrap a list in your implementation. But you can't guarantee that the wrapped list is not empty. You will notice this in your implementation of you have to resort to `withDefault` with a value you pull out of thin air.

The gist of the assignment was to reflect on the "classical" definition of a List

```elm
type List a
   = Empty
    | Cons a (List a)
```

Which basically says: a list is either empty or it is an element and the rest of the elements.

For a non-empty list the Empty case is problematic. Changing this to the following would have solved the assignment.

```elm
type NonEmptyList a
    = Value a
    | Cons a (NonEmptyList a)
```

**Comment by luukverberkt** [comment]
@dvberkel 

What do I need to change in this assignment?

**Comment by luukverberkt** [comment]
@dvberkel 

I see what you mean by your comment.

Can you tell me what I need to do to pass this assignment?

**Comment by dvberkel** [comment]
Passing the assignment can be done by closing this issue.

Owning the issue would mean to re-implement it. But if you understand the direction I am suggesting and are confident that you could work out the consequences closing is ok.
